org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.home=/home/paulo/AndroidStudioProjects/WebcamPhone/jdk17
org.gradle.java.installations.paths=/home/paulo/AndroidStudioProjects/WebcamPhone/jdk17
android.useAndroidX=true
android.enableJetifier=true
